### ISSUE TITLE
What's the recommended process for upgrading only one non-direct dependency?

### ISSUE THREAD

**Issue by kylegibson** [peterdemin/pip-compile-multi#109]
I understand that if I bump a version in base.in, I can use --no-upgrade to prevent all other packages in base.txt from being upgraded. 

However, how would I upgrade a package that is only defined in base.txt to a specific verison (and not necessarily the latest) ? It seems like it might be enough to just directly edit base.txt and change the desired version - is that fine?

What if hashes are enabled? Manually changing the version is easy enough, but then the hashes won't match.

Thanks

**Comment by peterdemin** [comment]
Hi Kyle, thanks for asking. When I deal with such tasks I do the following.
1. I have 2-step compilation process. First `.in` -> `.txt`, than `.txt` -> `.hash` with `--no-upgrade`. It's good for cases where you can't use hashes for installation. For example at my work we have PyPI proxy setup, that has it's own `.whl` files with hashes differing from the original PyPI.
2. With this setup, when I want to upgrade just a single subdependency, I remove it from `.txt` file and run compilation with `--no-upgrade`. pip-tools won't find existing constraint and will use the freshest version from allowed. Then `.hash` will regenerate in the usual way.

I recommend having this in a Makefile, like in this project: https://github.com/peterdemin/awsme/blob/master/Makefile#L54.
`make lock` runs this tox command: https://github.com/peterdemin/awsme/blob/master/tox.ini#L51

I should really add this to the docs...

**Comment by kylegibson** [comment]
Would it be possible and reasonable for pip-compile-multi to provide an option/command that could make that process easier? 

pip-compile-multi --directory=foo --generate-hashes=base --no-upgrade --allowed-upgrades="awesome==1.2.3 otherpackage ..."

**Comment by peterdemin** [comment]
So I've been thinking about this for a while. 
1) this option is not a good fit for CLI v1, as `pip-compile-multi` is meant to be a convenience wrapper for `pip-compile` that puts conventions before options.
2) CLI v2 looks more appropriate (currently in beta). I envision this as `$ requirements upgrade awesome otherpackage` while having the rest of options in the `.ini` file.

I see the benefits of having this feature, but I also don't have any timeline for CLI v2 release.

**Comment by JonathanRRogers** [comment]
Version 1.4.0 adds the --upgrade-package option to CLI v1, mirroring that of pip-compile.
