### ISSUE TITLE
Support for generating platform specific requirements

### ISSUE THREAD

**Issue by joshbarth** [peterdemin/pip-compile-multi#145]
I want to be able to define a requirement that will only work on a particular platform, but will be included in the requirements.txt file when generated from any other platform. The specific package is tensorflow-gpu==2.0.0a0, which is only available on Linux, but I need to be able to generate a "prod.txt" that includes it. Of course, it would break if ran on any other platform, but I just want to be able to generate the requirements, not actually install them, on platforms other than Linux

**Comment by peterdemin** [comment]
As far as I know, pip-tools is only capable of resolving dependencies for current OS.
As a workaround for your specific case I might consider following setup:
`prod.in` has all the packages that are available on both windows and linux.
`linux.in` has Linux specific packages and is not touched when upgrading packages under Windows.
`linux-prod.txt` is a static file (not the compiled one) with following contents:
```
-r prod.txt
-r linux.txt
```

**Comment by joshbarth** [comment]
Thanks, that's a fine work around for now. Will maybe open a issue with pip-tools
