### ISSUE TITLE
`-P` now has two meanings

### ISSUE THREAD

**Issue by tgs** [peterdemin/pip-compile-multi#147]
`-P` means both "just upgrade this package" and "forbid .post versions" - this changed the meaning of -P from before.

**Comment by peterdemin** [comment]
Ah, what a shame. I wonder why didn't click catch it...
Anyway I want to go with the "just upgrade this package" meaning, since that's what `pip-compile` uses.
What do you think about changing `--forbid-post` short option to lowercase `-p`?

**Comment by tgs** [comment]
Lower case p would be fine with me

**Comment by peterdemin** [comment]
Fixed in 1.5.0
