### ISSUE TITLE
Add option to use pip-compile cache

### ISSUE THREAD

**Issue by peterdemin** [peterdemin/pip-compile-multi#149]
Currently `pip-compile-multi` always executes `pip-compile` with `--rebuild` flag, which causes significant performance degradation (but is more reliable in edge cases).
Add option `--use-cache` that will remove `--rebuild` flag from the call to `pip-compile`.
This way, the default behavior will be slow but safe, and those who are feeling lucky can save themselves a few minutes.

**Comment by rpkilby** [comment]
Could you clarify how the `pip-compile` cache is unsafe? Is this an issue in `pip-tools`, or is it an edge case based on how `pip-compile-multi` works? Are there related issues/discussions in `pip-tools`?
