### ISSUE TITLE
Preserve pip requirement options in the generated output files 

### ISSUE THREAD

**Issue by john-bodley** [peterdemin/pip-compile-multi#159]
Though `pip-compile-multi` leverage  the `pip` requirement options like `--index-url` specified in the `.in` files when generating the dependencies, i.e.,  

**requirements/base.in**:
```
--index-url <url>
click
pip-tools
toposort
```

**requirements/test.in**:
```
--index-url <url>
-r base.in
mock
```

these aren't preserved in the generated `.txt` files and thus one needs to re-specify these when installing the requirements, i.e.,

```
pip3 install --index-url <url> -r requirements/test.txt
```

I was wondering whether it would make sense to preserve these options in the generated `.txt` files. Note `pip-compile` (from `pip-tools`) preserves these, i.e., 

```
pip-compile requirements/base.in
```

produces, 

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements/base.in
#
--index-url <url>

click==7.0
pip-tools==4.1.0
six==1.12.0               # via pip-tools
toposort==1.5
```

**Comment by john-bodley** [comment]
@peterdemin is there any reason to omit the index from `pip-compile` via the `--no-index` argument (per [here](https://github.com/peterdemin/pip-compile-multi/blob/c148ebc2d1f52a32cbf66e7290e924ceb7c73d5a/pipcompilemulti/environment.py#L105))?

**Comment by peterdemin** [comment]
The idea behind removing `--no-index` from `.txt` files is that the index URL is specific to the environment, not to the source packages. For example, you can have PyPI mirrors with different URLs in development and production environments. But the package will be the same.
Usually, we set `index` URL in `/etc/pip.conf` and do not pass it to the pip or pip-compile commands.

**Comment by peterdemin** [comment]
@john-bodley although I never needed to annotate index URL in `.txt` files, I realize, that other projects may have different requirements. So if you find this feature useful, your PR is welcome. Should pretty similar to `--use-cache` feature.
