### ISSUE TITLE
editable not supported

### ISSUE THREAD

**Issue by mmerickel** [peterdemin/pip-compile-multi#162]
In my `base.in` I have an editable dependency like `-e file:src/foo#egg=foo` and if I use pip-compile directly it dumps that same statement out into `base.txt` but using `pip-compile-multi` the output strips the `-e` prefix and dumps out directly `file:src/foo#egg=foo`. I expect it to preserve the `-e` prefix.

**Comment by mmerickel** [comment]
looks like this is a dup of #23 but I think there should be an option to preserve the editable mode flag

**Comment by peterdemin** [comment]
I think it makes sense to preserve `-e` flag if the package URL starts with `file:`. PR is welcome.

**Comment by peterdemin** [comment]
I just checked, and the flag works as expected. `-e file:.` in `requirements.in` files translates into `-e file:.` in the `requiremetns.txt` file.

**Comment by zuckerruebe** [comment]
Is this resolved? If so on what release? I think I'm seeing this behaviour on the lastest stable release on PyPI... Cheers.

**Comment by zuckerruebe** [comment]
I got around the issue by dropping the `#egg=pytrnsys-gui` part. Didn't actually need it and couldn't remember any more why it was there. Still the silent dropping of the `-e` did bite me. I don't think it should be dropped in any case.

**Comment by peterdemin** [comment]
Look like # part broke the file: detection. Would you be open to filing a fix PR?
