### ISSUE TITLE
cannot use without activating

### ISSUE THREAD

**Issue by mmerickel** [peterdemin/pip-compile-multi#163]
Without activating the virtualenv in the shell, pip-compile-multi cannot run properly.

```
$ python3 -m venv env
$ env/bin/pip install pip-compile-multi
$ env/bin/pip-compile-multi
<snip>
FileNotFoundError: [Errno 2] No such file or directory: 'pip-compile': 'pip-compile'
```

Ideally pip-compile-multi would invoke pip-compile using its python entrypoint instead of finding it on the PATH. Something like `args = [sys.executable, '-m', 'piptools', 'compile', *rest]`. This would enable it to work even if pip-compile isn't on the path, so long as it's installed into the same virtualenv.

**Comment by peterdemin** [comment]
I like it. Maybe it will even allow building pip-compile-multi as a pex.  [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](http://makeapullrequest.com)

**Comment by peterdemin** [comment]
Fixed
