### ISSUE TITLE
Feature: Using sub-directories to organize '/requirements'.

### ISSUE THREAD

**Issue by bengineerdavis** [peterdemin/pip-compile-multi#164]
(accidentally posted this before I was done, so you'll see a weird edit history!)

Thank you for finally making pip-tools a practical item for me--I've had a lot of fun exploring and applying this tool to some projects.

This issue has potentially a lot of overlap with #128 . The big difference is that issue is about managing separate requirements directories in the same repo and this is about managing files within a single requirements directory.

I see an opportunity to help maintain readibility and context within the directory structure of any given project that uses your pip-compile-multi.

As of right now, running `pip-compile-tools` requires that every 'input' file and every 'output' file live as siblings at the `./requirements` directory level. Let's use a simpler version of the examples used in your [how-to.md file](https://github.com/peterdemin/pip-compile-multi/blob/master/how-to.md)
```
project/
  requirements/  
    base.in
    base.txt
    bash.hash    
    test.in  # takes in '-r base.in'
    test.txt
    test.hash
    local.in  # takes in '-r test'
    local.txt
    local.hash
```

Without a way to better group these files, this leads has the potential for a huge amount of files to parse by eye.

A better way would be to provide a command line option that could parse requirement subdirectories so that I can group files by environment or file type (although, there may be many more potential use cases for this, those are the two most appealing to me). 

Examples:
This:
```
project/
  requirements/  # pip-compile-multi loops through each subdirectory
    base/
      base.in
      base.txt
      bash.hash
    test/        
      test.in  # takes in '-r base.in'
      test.txt
      test.hash
    local/
      local.in  # takes in '-r test'
      local.txt
      local.hash
```
Or maybe this:
```
project/
  requirements/  # pip-compile-multi loops through each subdirectory
    in/
      base.in
      text.in
      local.in
    text/        
      base.txt
      test.txt
      local.txt
    hash/
      base.hash
      test.hash
      local.hash
```
Current you have the `-d --directory` option, which works fine on `.in` file inputs so long as that file does not include statements such as `-r file`, etc. When I played around with this in some bash scripts, it seems like your topology sort algorithm current can't parse through sub-directories to find `-r file` dependencies while it is creating the resolution order.

I imaged the command line format could follow in the style of the `tree` bash utility: https://linux.die.net/man/1/tree

`pip-compile-multi -sd <integer>` or `pip-compile-multi -L <integer>`

Or,

`pip-compile-multi -d --L <integer>`  # expanding your current `-directory` option.

I feel like this could be done with a deque/ordered_dict that can map the output of dependency files into the correct subdirectories--which would be discovered and stored/tracked during the execution of the command, above.

I'm open to contributing to this problem, although I'm fairly new to working on someone else's project, and would be curious to know what the more experienced think would be good implementations of this, or if this is feasible at all (limitations of pip-tools, and other dependencies of this package).

**Comment by peterdemin** [comment]
Hi, thanks for the kind words. I like the idea. The first option requires making discovery recursive (just notice that for pip-compile to work it should be `-r ../base/base.in` instead of `-r base.in`).
As some projects have requirements files in the project's root, this shouldn't be the default behavior. I'm not sure about accepting the number of recursion levels in `-L`. Maybe just `-R` will suffice for activating a recursive descend?
The second option needs the new command-line argument for the output directory. I propose `-O <dir name>`.
I'm happy to review the PRs. I suggest implementing these features in separate PRs and start with the first one. I organized features in separate files, it helps with keeping a track of them, but also adds a layer of indirection. Not sure if it's easy to understand, so feel free to ask about how it works.

**Comment by bengineerdavis** [comment]
Those ideas sound good to me. I do prefer using this utility at the root level of the project, like a venv.

**Comment by peterdemin** [comment]
All features are called from `pipcompilemulti/features/controller.py` Following the example of add_hashes.py, method `pin_options` is called from `FeaturesController.pin_options`, which in turn is called from [pin_command](https://github.com/peterdemin/pip-compile-multi/blob/0a9858a444faed4b976a42657d1d67a95031c369/pipcompilemulti/environment.py#L99-L108) as `FEATURES.pin_options(self.name)`.
`FEATURES` is the instance of FeaturesController.

**Comment by bengineerdavis** [comment]
That helped a lot, thank you! So I see how you're assembling the commands now (which is into that list that pin_command creates, right?). How to you output those commands (from controller.py?) into the terminal for pip-compile to execute?

**Comment by peterdemin** [comment]
`pin_command` is used in [create_lockfile](https://github.com/peterdemin/pip-compile-multi/blob/0a9858a444faed4b976a42657d1d67a95031c369/pipcompilemulti/environment.py#L53).
(It doesn't output to a terminal, but uses Python's subprocess to run pip-compile)
Generally, I use Find in Files or `grep` to find how the method is used.

**Comment by bengineerdavis** [comment]
I've been doing a lot of research on how to approach this, since I've never done a feature for another repository before and coming back to this with some ideas surrounding the use of pathlib from the std library to give us some flexibility so that default and recursive option commands for this feature will work.

**Comment by peterdemin** [comment]
I’m not too familiar with pathlib. But it was added in Python 3.4, and pip-compile-multi is conservative in supporting Python 2.7 a bit longer.
But that’s not set in stone if the benefit of dropping old Python version is high enough for implementation of this feature.

I had to dig a great deal inside the click library to spread options across files. It still feels hacky with this dynamic decoration. My hope was that you won’t need to debug it in order to successfully use it.

**Comment by bengineerdavis** [comment]
I'm open to changing things once I get something in a branch on my fork,
and then I can link here. Can you go over more in-depth how you're using
the click library--and which parts--so I can read up on documentation?

**Comment by peterdemin** [comment]
pip-compile-multi uses `click.option` decorator to add options to a command.
The decorator parameters are composed and applied here: https://github.com/peterdemin/pip-compile-multi/blob/master/pipcompilemulti/features/base.py#L29
Command wrapper pops option value and saves it to OPTIONS global dict: https://github.com/peterdemin/pip-compile-multi/blob/master/pipcompilemulti/features/controller.py#L58

**Comment by peterdemin** [comment]
I'm back to this issue (almost a year later). The new approach is to follow the references to other directories, which could potentially solve this use-case.
