### ISSUE TITLE
#via comments leak full system path with new pip-tools versions

### ISSUE THREAD

**Issue by HALtheWise** [peterdemin/pip-compile-multi#166]
New versions of pip-tools (4.5.1) leave comments of the form `# via -r requirements.in` next to packages that are directly mentioned. Unfortunately, when executing `pip-compile-multi -d /home/{me}/some_directory` as we typically do, it makes those comments read `# via -r /home/{me}/some_directory/requirements.in` which is really annoying and also leaks the full system path into the repo, making the compile non-reproducible.

Our workaround for now is to instead execute `pip-compile-multi` with the working directory set to the target directory, and use `-d ./`, but that's a bit of a mess and still results in `# via ./requirements.in` which isn't ideal. Ideally, `pip-compile-multi` would set the working directory when it calls out to `pip-compile` to whatever is in the `-d` flag, and avoid this issue.

**Comment by peterdemin** [comment]
Sounds reasonable. Can you put up a PR for that?
