### ISSUE TITLE
clarify vs. pip-compile

### ISSUE THREAD

**Issue by belm0** [peterdemin/pip-compile-multi#190]
I read https://pip-compile-multi.readthedocs.io/en/latest/why.html, but that doc didn't cover the advantages over `pip-compile` and its layering workflow.

It's likely my lack of understanding or not hitting the cases where pip-compile-multi would be a good value.  But having better docs on this may help others as well.

**Comment by peterdemin** [comment]
Thanks for the comment, I'll try to clarify it.

**Comment by belm0** [comment]
Would you point me to the commit or PR with the changes?

Also I noticed the doc is outdated about PipEnv.  It was misunderstood as the one official way forward and having a good design and implementation, none of which is true.
