### ISSUE TITLE
Allow specification of target system

### ISSUE THREAD

**Issue by rdturnermtl** [peterdemin/pip-compile-multi#193]
Currently, `pip-compile-multi` uses the host system when compiling requirements (OS and Python version).

There should be options to compile what the requirements would be on any specific Python version and OS. For instance, `pip download` works this way and allows the user to download the package wheel for a different system:
https://pip.pypa.io/en/stable/reference/pip_download/#examples
For example,

```bash
pip download \
    --only-binary=:all: \
    --platform linux_x86_64 \
    --python-version 3 \
    --implementation cp \
    --abi cp34m \
    SomePackage
```

For instance, `ipython` requires `appnope` on Mac, but not on Linux. It should be possible to compile the linux requirements on Mac and vice-versa.

Also, for example, `importlib.metadata` is a built-in for `>= Py 3.7` but otherwise needs to put into Python requirements. It should be possible to compile the requirements for `Py 3.5` on `Py 3.7` and vice-versa.

**Comment by peterdemin** [comment]
That's not feasible unless underlying library supports it: [pip-tools](https://github.com/jazzband/pip-tools)
