### ISSUE TITLE
Regression in v1.5.9 for file URLs using relative paths

### ISSUE THREAD

**Issue by john-bodley** [peterdemin/pip-compile-multi#196]
There seems to be a regression between v1.5.8 and v1.5.9 causing issues when referencing relative paths with [file URLs](https://www.python.org/dev/peps/pep-0440/#file-urls) which is common for leveraging the `install_requires` field in `setup.py`, i.e., specifying `-e file:.`. 

I believe the regression was introduced in https://github.com/peterdemin/pip-compile-multi/pull/167 (cc @HALtheWise) as it seems like `pip-compile-multi` is running `pip-compile` from within the `requirements` (working) directory hence why comments of the form in v1.5.8, 

```
# via -r requirements/base.in
```

and now defined in v1.5.9 as 

```
# via -r base.in
```

which is problematic for relative paths, i.e., (in v1.5.9):

```
> cat requirements/base.in
-e file:. 
```

```
> pip-compile-multi
Locking requirements/base.in to requirements/base.txt. References: []
ERROR executing pip-compile --no-header --verbose --rebuild --upgrade --no-index --output-file base.txt base.in
...
FileNotFoundError: [Errno 2] No such file or directory: '<hidden>/requirements/setup.py'
```

Note replacing `-e file:.` with `-e file:..` works from `pip-compile-multi`'s standpoint but fails when you try to `pip install -r requirements/base.txt`. One could remedy this by `cd`'ing to the `requirements` directory but this seems like an anti-pattern.

**Comment by HALtheWise** [comment]
It seems like there will always be _somewhere_ where pip can be executed from, and everywhere else will fail. I'm 100% onboard with the idea that the location should be the repo root rather than the requirements directory, so definitely we should fix this. My change was originally because we were seeing _absolute_ paths show up in the output files /home/... which is definitely unacceptable as well, so perhaps there's a good solution that prevents both issues?

**Comment by john-bodley** [comment]
@HALtheWise was this because you were using the `-e .` construct? If so this is a known problem per https://github.com/jazzband/pip-tools/issues/204. It seems if you use `file:` i.e., `-e file:.` (per [this](https://github.com/jazzband/pip-tools/issues/204#issuecomment-550051424) comment) the resulting output paths will remain relative.

**Comment by peterdemin** [comment]
Reverting this would re-open issue from #166, right @HALtheWise?
I'm confused with a way pip-compile handles paths. Does it make sense to fix up `# via ...` comments in pip-compile-multi?
CC @john-bodley

**Comment by john-bodley** [comment]
@HALtheWise It would be good to see if using the `file:` prefix resolves your `# via ...` absolute path issue.

**Comment by john-bodley** [comment]
@peterdemin do you have any further thoughts on this? Note we leverage the `pip-compile-multi` pre-commit hook and would love to be able to run `pre-commit autoupdate` to update all the pre-commit hooks however this isn't currently viable given the latest version `1.5.9` does work with relative file paths.

**Comment by peterdemin** [comment]
@john-bodley I changed the way files are referenced, now they always use a relative path.
Please verify if the issue still holds and reopen this if needed.

**Comment by john-bodley** [comment]
Thanks @peterdemin. Looking through our code it seems like we're no longer restricting the version of `pip-compile-multi` in our input files which would indicate that the issue has been resolved.
