### ISSUE TITLE
Embedded update command missing arguments

### ISSUE THREAD

**Issue by rpkilby** [peterdemin/pip-compile-multi#199]
Hi 👋 . `pip-compile`'s output embeds the command used to generate a given file.  e.g., 
```sh
pip-compile --generate-hashes --output-file=foo.txt requirements.in
```
Currently `pip-compile-multi` just writes `pip-compile-multi`, but I'd argue it should mimic `pip-compile`'s behavior, as it's useful in case you accidentally forget the command you used to specifically generate the output. 

That said, some consideration needs to be put into what arguments should be in the output command. e.g., `pip-compile` doesn't include `--upgrade`, and it normalizes its options (`-o foo.txt` =>  `--output-file=foo.txt`).

**Comment by peterdemin** [comment]
There're two parts to this issue.
1. You can override the whole header using [custom header](https://pip-compile-multi.readthedocs.io/en/latest/features.html#custom-header)
2. v2 (alpha) uses config file instead of command-line parameters to standardize on invocation.

**Comment by peterdemin** [comment]
Feel free to re-open if I'm missing something.

**Comment by rpkilby** [comment]
If you're punting all development on the old CLI in favor of the v2 CLI, then that's fair. I would suggest though that you add something in the documentation about how to enable it. I completely missed that it could be enabled with an env var.
