### ISSUE TITLE
Allow for `git+ssh://git@gitlab.com/<user>/<my_lib>@v<version number>` in the requirements.in

### ISSUE THREAD

**Issue by SebastianoX** [peterdemin/pip-compile-multi#201]
Hello!
Thanks for developing `pip-compile-multi`! It is a great tool that allow for reproducibility in different circumstances!

Now, I am looking into installing a private python library directly from the repo url, auth with ssh.
To install it from command line, I would just run:
```
pip install git+ssh://git@gitlab.com/<user>/<my_lib>@v<version number>
```

To install it from a traditional requirements.txt, adding the line
```
git+ssh://git@gitlab.com/<user>/<my_lib>@v<version number>
```
sill does the job. 

Though if I add the same line in the `requirements.in` when calling `pip-compile-multi`, there is no trace of `my_lib` in the `requirements.txt`.

Do you have a workaround or do you plan to allow for url-based requirements in the future?

Thanks

**Comment by peterdemin** [comment]
I would appreciate further research on this topic. If pip-tools' pip-compile supports this syntax, maybe it just needs to be added to a list of regexes in pip-compile-multi.

**Comment by SebastianoX** [comment]
After some further testing I realised that pip-compile and pip-compile-multi BOTH works with the url in the `.in` file, in contradiction with what I said above.
The issue was opened after I was misled by the fact that the target library was `flit`-installable and not `pip`-installable. 
The issue is already solved, thanks for your time!
