### ISSUE TITLE
Hashing option which ignores comments and sorts dependencies

### ISSUE THREAD

**Issue by danielgordon10** [peterdemin/pip-compile-multi#215]
It would be great if there was an option which creates/checks hashes but ignores things that are in comments. For example:

```python
import hashlib

def get_hash_ignore_comments(fi):
    lines = [line.split('#')[0].strip() for line in open(fi)]
    lines = '\n'.join(sorted([line for line in lines if len(line) > 0]))
    hasher = hashlib.sha1()
    hasher.update(lines.encode('utf-8'))
    file_hash = hasher.hexdigest()
    return file_hash
```

Would it be possible to add this feature?

**Comment by peterdemin** [comment]
Sounds good, another thing is to coerce all line endings to Unix-style. See #148 for details.
I'll be happy to review/merge the pull request.

**Comment by peterdemin** [comment]
Another important point - check for both new and old ways of hashing during verification.
