### ISSUE TITLE
Comments on mutliple newlines change?

### ISSUE THREAD

**Issue by hawksight** [peterdemin/pip-compile-multi#218]
This isn't an issue really, but something I've noticed that's changed since I used pip-compile-multi last year.

Alll the generated .txt files now post `#` commends where they are required on newlines, rather than inline and comma seperated. Eg. it now look like:

```
# SHA1:d86f8da703a23055b343ba7dff8d05e274d654ed
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
boto3==1.16.48
# via credstash
botocore==1.19.48
# via
#   boto3
#   s3transfer
cachetools==4.2.0
# via google-auth
certifi==2020.12.5
# via requests
cffi==1.14.4
# via
#   cryptography
#   google-crc32c
```

Instead of:

```
# SHA1:d86f8da703a23055b343ba7dff8d05e274d654ed
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
boto3==1.14.49            # via credstash
botocore==1.17.49         # via boto3, s3transfer
cachetools==4.1.1         # via google-auth
certifi==2020.6.20        # via requests
cffi==1.14.2              # via cryptography, google-crc32c
```

I couldn't see any reference to this in a change log or release unless I've just missed it?
Is this intended to make git diffs more readable?

**Comment by davidism** [comment]
pip-compile started outputting the `via` comments on separate lines, and changed the format for multiple values to be indented. This seems to have made pip-compile-multi's formatting a bit confusing to read, especially when extending `.in` files.

**Comment by peterdemin** [comment]
You can downgrade pip-tools to previous version. I think this change was introduced in 5.5 branch.

**Comment by hawksight** [comment]
Thanks both, I'd rather stay up to date I was just surprised by the change and couldn't see it referenced.
Would be nice to have the choice of format though.
Also to say this is a great library @peterdemin, saves me loads of time and effort.

**Comment by peterdemin** [comment]
Fixed, please upgrade.
