### ISSUE TITLE
-e flag omitted for specific git commits

### ISSUE THREAD

**Issue by einarstensson** [peterdemin/pip-compile-multi#23]
OS Description: Ubuntu 16.04.4 LTS
Release: 16.04

In order to clone a specific commit of a dependency, you can use:
`-e git+https://github.com/owner/repository.git@branch_or_commit`

(see: https://stackoverflow.com/a/37398622)

When running pip-compile-multi with with an .in file containing e.g.:
_build.in_
-e git+https://github.com/ansible/ansible-container.git#egg=ansible-container[docker]
pip-compile-multi
pylama
etc.

... the -e flag is omitted in the resulting .txt file, causing the required cloned src folder to not be created when running e.g. `pip install -r requirements/build.txt`

_build.txt_
git+https://github.com/ansible/ansible-container.git#egg=ansible-container[docker]
etc.

**Comment by peterdemin** [comment]
`-e` flag is removed on purpose. I think it was done to workaround a bug in pip or something.
Do I understand correctly, that you want to have `-e` in `.txt` file?

**Comment by peterdemin** [comment]
Hmm... I'm reviewing the linked issue (and issues linked to that) and don't really see why `-e` should be removed from the `.txt` file... The issue is about keeping it in the `.in` file.

**Comment by peterdemin** [comment]
I compared what happens with and without `-e` flag. With `-e` pip clones repo to `$VIRTUAL_ENV/src/ansible-container` and creates corresponding `.pth` file.
Without `-e` flag, it clones repo to temporary directory and installs it in regular way, then deletes the temporary directory.
Is there a particular reason you want to keep source repo after the installation?

**Comment by einarstensson** [comment]
Thank you! Interesting to read through the links you posted.

I believe it's because we want to install ansible-container in a docker container during our builds. I'm not entirely sure why or how yet though. It seems a bit strange to me so perhaps it's a very unusual use-case. I'll close the issue.
