### ISSUE TITLE
Allow --extra-index-url persistence in files

### ISSUE THREAD

**Issue by danpalmer** [peterdemin/pip-compile-multi#262]
We're moving from `pip-compile` to `pip-compile-multi` and have found a slight difference in behaviour. I'm not sure if this is a bug, a missing feature, or an intentional decision so apologies if I get this a bit wrong.

Currently we do something like this:

```
# requirements.in
--extra-index-url https://internal/
my-internal-library
```

When running `pip-compile` (with no args!) this results in the following, with the extra index URL preserved by default.

```
# requirements.txt
--extra-index-url https://internal/
my-internal-library==1.0 # via requirements.in
```

The same input file with `pip-compile-multi --no-upgrade` results in:

```
# requirements/app.txt
my-internal-library==1.0
```

This then doesn't install because there is no `--extra-index-url` argument to `pip install`.

The way to achieve the same thing is to run `pip-compile-multi --no-upgrade --extra-index-url=https://internal/ --annotate-index`. Each argument requires users to have more understanding of how the tool works and how a codebase utilises the tool, and introduces scope for human-error when this isn't known.

Being able to specify everything necessary in the source files keeps this knowledge in version control, in code review, and makes it easier to use the tools.

If implemented, to maintain consistency with the current options in the tool I'd expect it to work roughly like this, which unfortunately doesn't currently work.

```
# requirements/app.in
--extra-index-url https://internal/
--annotate-index
my-internal-library
```

**Comment by peterdemin** [comment]
Pip compile multi uses index-url for URLs that are saved in files and extra-index-url for ephemeral URLs passed as an argument.

Docs:
https://pip-compile-multi.readthedocs.io/en/latest/features.html#add-index-url-annotation

The naming is confusing. I’m trying to remember why annotate-index is disabled by default. I need to think about it. 

In the meantime time, could you please confirm that this solution works for your case: use index-url instead of extra-index-url in `.in` file and pass `--annotate-index` argument?

**Comment by peterdemin** [comment]
Hey @danpalmer, I'm back to this issue. I just found this in the pip docs, thought you might be interested:
> Using `--extra-index-url` option to search for packages that are not in the main repository (such as private packages) is unsafe, per a security vulnerability called **dependency confusion**: an attacker can claim the package on the public repository in a way that will ensure it gets chosen over the private package.
> Use the `--index-url` option in pip’s configuration file or command line to specify the feed, overriding the default. Avoid the `--extra-index-url` option, which is additive and may lead to having multiple indexes.

**Comment by peterdemin** [comment]
Having `--annotate-index` on by default would not play well with a multi-stage private package index setup.
And that would be a backward-incompatible change.
Another consideration is that using `--extra-index-url` is bad practice from a security perspective.
Closing for now. Feel free to reopen if I missed something.
