### ISSUE TITLE
--no-build-isolation flag doesn't get passed to piptools compile

### ISSUE THREAD

**Issue by schmidt-jake** [peterdemin/pip-compile-multi#312]
#311 added support for pip / pip-compile's `--build-isolation / --no-build-isolation` flag, but specifying `--no-build-isolation` does not actually pass that flag to the underlying `piptools compile` command.

To reproduce, I run the following on some requirements files that require build isolation to be disabled for locking:
```bash
pip-compile-multi --directory=requirements/ --no-build-isolation
```

Output:
```bash
ERROR executing python3.8 -m piptools compile --no-header --verbose --rebuild --upgrade --no-emit-index-url --output-file requirements.txt requirements.in

...
```

I suspect the issue is `pip-compile-multi` is dropping the `--no-build-isolation` flag somewhere because if I take the failing `piptools compile` command and add `--no-build-isolation`, it compiles successfully:

```bash
python3.8 -m piptools compile --no-build-isolation --no-header --verbose --rebuild --upgrade --no-emit-index-url --output-file requirements.txt requirements.in
```

Looking into how I can write a test for this.

**Comment by peterdemin** [comment]
Released in https://pypi.org/project/pip-compile-multi/2.4.5/
