### ISSUE TITLE
Add support for pip-compile's `--emit-trusted-host / --no-emit-trusted-host` flags

### ISSUE THREAD

**Issue by philblckwd** [peterdemin/pip-compile-multi#351]
The flags `--emit-trusted-host / --no-emit-trusted-host` from `pip-compile` would be useful to expose so that you can control whether the `--trusted-host` option is printed to the requirements files. Currently I have to remove it manually from each of my requirements files after upgrading dependencies.

Interestingly the `--index-url` and `--extra-index-url` are not printed in the requirements file whereas if I ran `pip-compile` without any flags, those flags are printed in the file, along with `--trusted-host`. Does `pip-compile-multi` automatically pass the `--no-emit-index-url` when invoking `pip-compile`?

Thanks in advance!

**Comment by peterdemin** [comment]
Thank you so much! I'll publish a new release later today.

**Comment by peterdemin** [comment]
Thanks again! This feature is released in version [2.5.0](https://pypi.org/project/pip-compile-multi/2.5.0/).

**Comment by philblckwd** [comment]
Awesome, thank you @peterdemin !
