### ISSUE TITLE
Provide a way to not treat some requirements files as references

### ISSUE THREAD

**Issue by SpecLad** [peterdemin/pip-compile-multi#386]
Let's say I have the following set of files:

`base.in`:

```
-r external/deps.in
a
```

`prod.in`:
```
-r base.in
b
```

`external/deps.in`:
```
c
```

What I want is for the output to look like this:

`base.txt`:
```
c==1.2.3
a==4.5.6
```

`prod.txt`:
```
-r base.txt
b==7.8.9
```

In other words, `external/deps.in` is not an environment, so it should not produce a requirements file of its own. Anything it contains should just be treated as if it's a part of `base.in`.

As far as I know, there's no way to do this with pip-compile-multi at the moment.

This would be helpful to reduce the number of pip-compile runs, as well as to permit more leeway with the version constraints. For example, `base.in` could constrain a package more tightly than `external/deps.in`, which doesn't work if `deps.in` is treated as a reference.

**Comment by peterdemin** [comment]
Have you tried --auto-resolve flag?

**Comment by SpecLad** [comment]
I have now. It's useful for the second problem, but not so much the first - in fact it adds an _extra_ pip-compile run, so the whole thing becomes even slower.

**Comment by peterdemin** [comment]
The versions are resolved only on the first run. All subsequent runs are faster because they re-use the constraints from the first call.

**Comment by SpecLad** [comment]
In my practice, each run still takes a really long time, so the fewer of them, the better.

Plus, purely from a conceptual standpoint, I don't consider `external/deps.in` to be an environment, so I don't need or want to have a corresponding `external/deps.txt`.

**Comment by peterdemin** [comment]
`--use-cache` can improve compilation time significantly.
I don't follow the concept behind `external/deps.in`. It's a requirements file, and it's referenced from the `base.txt`. What's the issue with its existence?
