### ISSUE TITLE
Fails with pip==23.1

### ISSUE THREAD

**Issue by nvaytet** [peterdemin/pip-compile-multi#389]
The error trying to run `pip-compile-multi` with `pip==23.1` is
```
File "/home/nvaytet/software/miniconda3/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 249, in get_dependencies
    wheel_cache = WheelCache(self._cache_dir, self.options.format_control)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by peterdemin** [comment]
pip-tools is playing catch up with pip. At the moment, I'd recommend downgrading pip. In the short while you can upgrade pip-tools

**Comment by cwegener** [comment]
This issue had already been resolved in this commit: https://github.com/peterdemin/pip-compile-multi/commit/617bc2758bf92a5c18f1306833b967a0c31a2cff prior to this issue being raised and pip-tools had already caught up. If you install pip-compile-multi from the latest master branch it will work fine.
