### ISSUE TITLE
Directories Skipped When Passing Multiple

### ISSUE THREAD

**Issue by ReneeErnst** [peterdemin/pip-compile-multi#408]
We have a repo with multiple sub-projects and want to use pip-compile-multi to help manage our requirements. After reviewing past issues, I was under the impression that I should be able to meet my goal by simply passing in multiple directory locations to pip-compile-multi. See https://github.com/peterdemin/pip-compile-multi/issues/164. 

Unfortunately, I hit issues where when I pass multiple directories, some are skipped in the process. No errors occur - they just don't run. I've created an example repo to demonstrate the repo. In the README I included the output for different scenarios. Please see that repo here: https://github.com/ReneeErnst/pip-compile-multi-issue. 

System info:
Mac OS Ventura 13.4.1
Python 3.9.7
pip-compile-multi version: 2.6.3

**Comment by peterdemin** [comment]
Directory parameter can not be supplied multiple times:
https://github.com/peterdemin/pip-compile-multi/blob/master/pipcompilemulti/features/base_dir.py
The last value overrides the previous ones.
```
pip-compile-multi -d c -d a -d b 
```
is equivalent to
```
pip-compile-multi -d b 
```
The reason why you see more than one directory used in the output is references. b/requirements.in has `-r ../c/requirements.in`

**Comment by peterdemin** [comment]
If you want all requirements to be locked together, you must have a parent requirements file that references all others.
If you add it, please take a look at https://pip-compile-multi.readthedocs.io/en/latest/features.html#autoresolve-cross-file-conflicts flag.

**Comment by ReneeErnst** [comment]
Thank you for the fast reply! I was using the directory input multiple times after reading this comment in another issue, but I see that was just discussing a possible option, not that it was implemented. 

I'm working with a large repo with many requirements files. I'll work on generating a parent reqs file.
