### ISSUE TITLE
Request: preserving CLI flags in generated text file(s)

### ISSUE THREAD

**Issue by jamesbraza** [peterdemin/pip-compile-multi#431]
With https://github.com/peterdemin/pip-compile-multi/tree/v2.6.3, after running `pip-compile-multi --backtracking --no-upgrade`, currently the output file looks like this:

```txt
# SHA1:abc123
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
...
```

Can we add preservation of CLI flags like `--backtracking` in the autogenerated `.txt` file(s)?

**Comment by peterdemin** [comment]
In general, I'm okay with smart_er_ generation of the header comment. Some flags should not be included, though, namely, --upgrade / --no-upgrade, and --upgrade-package. Other flags seem to be stable for the project.
Would you be open to contributing a PR that adds a new CLI flag to enable the flag passthrough?
I prefer this to be optional at first, and we can make this enabled by default in future releases.
I suggest naming the flag as `-w, --write-options`.

**Comment by peterdemin** [comment]
Closing due to lack of traction
