### ISSUE TITLE
Verify compiled files are up-to-date

### ISSUE THREAD

**Issue by peterdemin** [peterdemin/pip-compile-multi#5]
During the run of `pip-compile-multi` calculate a hash of `.in` file contents.
Save this hash in generated `.txt` on the first line with some special formatting.
In the new command `pip-compile-multi verify` recalculate hashes for `.in` files and compare them against parsed from `.txt` files.
Report which files need recompilation and return non-zero exit status if any.

**Comment by rht** [comment]
(Note: I think as of currently, 1.1.5 is sufficient for replacing Zulip's `tools/update-locked-requirements`.)
