### ISSUE TITLE
future should not be blanket-ignored in py3

### ISSUE THREAD

**Issue by Callek** [peterdemin/pip-compile-multi#76]
I have a project using python-jose and `future` is omitted in py3 with no recourse, but it does install fine in py3.

`pip-compile` does properly add it. and there is no mechanism to override this from the py3 ignore list.

Was added as an ignore in https://github.com/peterdemin/pip-compile-multi/commit/2d2ef07dd0be4cf58c55ad785db349e6eb94e856  perhaps add it as a p3 only default for ignore (and let us specify a blank ignore list?)

**Comment by peterdemin** [comment]
I see, sorry for the need to build workarounds.
I just tried to install `future` in Python 3.4, 3.5 and 3.6.
Originally this condition was added to work around a bug in pip: https://github.com/zulip/zulip/blob/master/tools/update-locked-requirements#L23
Apparently, this is no longer needed. I'll release a fixed version at the earliest convenience.
Thanks for reporting!

**Comment by peterdemin** [comment]
I released 1.2.2 with the fix.
