### ISSUE TITLE
Options must be specified before verify subcommand

### ISSUE THREAD

**Issue by merwok** [peterdemin/pip-compile-multi#83]
Hello and thanks for publishing this tool!

My projects tend to have four or five requirements files using the `.in/.txt` convention in a `deps` directory.  pip-tools lacks a mode to convert many files at once (https://github.com/jazzband/pip-tools/issues/532) and has no config file for options (https://github.com/jazzband/pip-tools/issues/604), so I have been using a wrapper script that is not very satisfying.

`pip-compile-multi -d deps --no-upgrades` works well to convert my files.
(The fact that upgrade is true by default is another issue!  Most of the time I added an item to the `.in` file and want to generate the lock file without changing what’s already there.)

`pip-compile-multi verify -d deps` does not work!

```
Usage: pip-compile-multi verify [OPTIONS]
Try "pip-compile-multi verify --help" for help.

Error: no such option: -d
```

`pip-compile-multi -d deps verify` works.

The documentation could include a working example of verify + options; it could also say that the options must come before the subcommand; the error message could be better.

**Comment by peterdemin** [comment]
Hi Éric, thanks for the feedback. I'm glad that pip-compile-multi provides a value to your projects.
I totally agree, verify should accept options as `Usage` states.
I'm short on time these days, but I'd be happy to merge a fix from a pull request if you don't mind opening one.

**Comment by merwok** [comment]
I haven’t used click but could look into this in a couple weeks!

**Comment by peterdemin** [comment]
Hi @merwok, don't mean to push, but maybe you just forgot ;-)

**Comment by merwok** [comment]
I have been busy and don’t think I will be able to work on this in the short term.

**Comment by peterdemin** [comment]
Fixed in 1.5.3

**Comment by merwok** [comment]
Great to hear!

Sorry you had a packaging issue.  I think the proper fix would be to amend setup.py to have `packages=["pipcompilemulti", "pipcompilemulti.features"]` rather than collecting the modules with MANIFEST.in and relying on luck to make the build/install commands process these files.

**Comment by peterdemin** [comment]
Thanks for the suggestion, I simplified MANIFEST and fixed setup.py.
